import '../imports/startup/client/Startup';
import './style.css';
import './signin.css';
import './dispense.css';
import './inventory.css';
import './status.css';
import './manage.css';
import './manage-users.css';
import './landing.css';
